bot:
  url: "127.0.0.1"
  port: 3001
  isDeBug: true
  taskTimeout: 5
  verifyKey: ""
  admin:
    - "1841375451"
VerifySocket:
  port: 2088
  解绑: "[CQ:at,qq=%QQ%] 您名下的全部CDK已解绑"
  查询授权: "[CQ:at,qq=%QQ%] 请查看私聊！如果没有发送请加我为好友"
  group:
    1074259430: "睡不醒"
    733492409: "语之头目"
    1049779311: "语之方块"
    980579456: "语之任务"
    308624938: "语之繁殖"
    833563627: "语之锻炼"
    608598991: "语之排位"
    434231618: "安静服务端"
    1034293477: "语之挂机战斗"
    1087055717: "语之比赛"
    858201887: "语之NPC"
  进群消息 : "[CQ:at,qq=%QQ%]\n感谢购买本插件！\n授权码为您的QQ号！\n请主动添加我为好友，发送消息查询授权获取授权信息。"
  加群添加CDK: true
